# version: '3'
# services:
#   user:
#     image: user
#     ports:
#       - "3001:3001"
#     command: node server.js

#   cart:
#     image: cart
#     ports:
#       - "3003:3003"
#     command: node server.js  

#   product:
#     image: product
#     ports:
#       - "3002:3002"
#     command: node server.js


version: '3'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  cart:
    build: ./backend/Cart
    container_name: cart
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3003:3003"
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/ecommerce

  product:
    build: ./backend/Product
    container_name: product
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3002:3002"
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/ecommerce

  user:
    build: ./backend/User
    container_name: user
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: "mongodb://admin:password@mongodb:27017/ecommerce?authSource=admin"

  frontend:
    build: ./front-end
    container_name: frontend
    restart: always
    depends_on:
      - cart
      - user
      - product
    ports:
      - "3000:3000"

    
