# version: '3'
# services:
#   user:
#     image: user
#     ports:
#       - "3001:3001"
#     command: node server.js

#   cart:
#     image: cart
#     ports:
#       - "3003:3003"
#     command: node server.js  

#   product:
#     image: product
#     ports:
#       - "3002:3002"
#     command: node server.js


version: '3'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  Cart:
    build: ./backend/Cart
    container_name: Cart
    restart: always
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/ecommerce

  Product:
    build: ./backend/Product
    container_name: Product
    restart: always
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/ecommerce

  User:
    build: ./backend/User
    container_name: User
    restart: always
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/ecommerce

  frontend:
    build: ./front-end
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

    
