apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: ruxs123/cart:latest
          ports:
            - containerPort: 3003
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mern-secrets
                  key: MONGO_ATLAS_URI  # Change to MONGO_LOCAL_URI if using self-hosted
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mern-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
