apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: ruxs123/product:latest
          ports:
            - containerPort: 3002
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mern-secrets
                  key: MONGO_ATLAS_URI  # Change to MONGO_LOCAL_URI if using self-hosted
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mern-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
