apiVersion: apps/v1
kind: Deployment
metadata: 
  name: product-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
       name: product
       labels:
         app: product
    spec:
      containers:
        - name: product
          image:  ruxs123/product:latest
          ports:
           - containerPort: 3002
          envFrom:
           - configMapRef:
               name: mern-config
           - secretRef:
               name: mern-secret


---

apiVersion: v1
kind: Service
metadata: 
  name: product-service
spec:
  type: ClusterIp
  seclector:
     app: product
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  