# # apiVersion: v1
# # kind: Secret
# # metadata:
# #   name: mern-secrets
# # type: Opaque
# # data:
# #   JWT_SECRET: "your-base64-encoded-secret"


# apiVersion: v1
# kind: Secret
# metadata:
#   name: mern-secrets
# type: Opaque
# data:
#   MONGO_USERNAME: "YWRtaW4="  # Base64-encoded "admin"
#   MONGO_PASSWORD: "cGFzc3dvcmQ="  # Base64-encoded "password"
#   MONGO_URI: "bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy9lY29tbWVyY2U="  # MongoDB URI
#   JWT_SECRET: "c2VjcmV0a2V5"  # Base64-encoded "secretkey"
#   STRIPE_SECRET_KEY: "c3RyaXBlX3NlY3JldF9rZXk="  # Base64-encoded Stripe Key (Replace if needed)

apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
type: Opaque
data:
  # Base64-encoded MongoDB Username & Password (Use same for both approaches)
  MONGO_USERNAME: "YWRtaW4="  # Base64-encoded "admin"
  MONGO_PASSWORD: "cGFzc3dvcmQ="  # Base64-encoded "password"

  # 🔹 Managed MongoDB (MongoDB Atlas / AWS DocumentDB)
  MONGO_ATLAS_URI: "bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQGNsdXN0ZXIubW9uZ29kYi5uZXQvZWNvbW1lcmNlP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ=="  

  # 🔹 Self-Hosted MongoDB Inside Kubernetes
  MONGO_LOCAL_URI: "bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy9lY29tbWVyY2U="  

  # 🔹 Additional Sensitive Information
  JWT_SECRET: "c2VjcmV0a2V5"  # Base64-encoded JWT Secret Key
  STRIPE_SECRET_KEY: "c3RyaXBlX3NlY3JldF9rZXk="  # Base64-encoded Stripe Secret Key

