# apiVersion: v1
# kind: Secret
# metadata:
#   name: mern-secrets
# type: Opaque
# data:
#   JWT_SECRET: "your-base64-encoded-secret"


apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
type: Opaque
data:
  MONGO_USERNAME: "YWRtaW4="  # Base64-encoded "admin"
  MONGO_PASSWORD: "cGFzc3dvcmQ="  # Base64-encoded "password"
  MONGO_URI: "bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy9lY29tbWVyY2U="  # MongoDB URI
  JWT_SECRET: "c2VjcmV0a2V5"  # Base64-encoded "secretkey"
  STRIPE_SECRET_KEY: "c3RyaXBlX3NlY3JldF9rZXk="  # Base64-encoded Stripe Key (Replace if needed)


