apiVersion: apps/v1
kind: Deployment
metadata: 
  name: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
       name: user
       labels:
         app: user
    spec:
      containers:
        - name: user
          image:  ruxs123/user:latest
          ports:
           - containerPort: 3001
          envFrom:
           - configMapRef:
               name: mern-config
           - secretRef:
               name: mern-secret


---

apiVersion: v1
kind: Service
metadata: 
  name: user-service
spec:
  type: ClusterIp
  seclector:
     app: user
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  