apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: ruxs123/user:latest
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mern-secrets
                  key: MONGO_ATLAS_URI  # Change to MONGO_LOCAL_URI if using self-hosted
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mern-secrets
                  key: JWT_SECRET
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mern-secrets
                  key: STRIPE_SECRET_KEY



---

apiVersion: v1
kind: Service
metadata: 
  name: user-service
spec:
  type: ClusterIP
  selector:
     app: user
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  