---
- name: Firewall changes
  hosts: all

  tasks:
  - name: Enable a service in firewall
    firewalld:
      port: 80/tcp     #for nginx87yy6666666
      permanent: true
      state: enabled

  - name: Reload firwalld
    service:
      name: firewalld
      state: reloaded
