- name: Firewall  Chnages
  hosts: all
  become: true

  tasks:
  - name: Enable a service in firewalld
    firewalld:
      port: 80/true
      permanent: true
      state: enable
    notify:
    - Reload Firewalld

  handlers:
  - name: Reload Firewalld
    service:
      name: firewalld
      state: reloaded