- name: Stopping process
  hosts: webserver
  become: true

  tasks:
    - name: Find and Kill process
      ignore_errors: yes
      shell: 'pgrep nginx | xargs kill'
   
    - name: Starting service
      service:
       name: nginx
       state: started
       



    